### ISSUE TITLE
Peer to peer code review - Day 5 - Block 2 - Module 1

### ISSUE THREAD

**Issue by jssol** [mirouhml/portfolio#10]
### :recycle: Requested changes :recycle:

Hello Ammar, good job so far :tada:
However, there are some issues that need to be addressed 🔧

- [ ] It is best practice to use semantic tags to improve the SEO of your website and accessibility: 
https://github.com/mirouhml/portfolio/blob/6308c85b2a1ecae3b2b975e5403e71f9b445cfd4/index.html#L22

**Benefits**
Using the `main` tag will be better for accessibility than `div`

- [ ] I suggest turning the logo into a link, this will improve the UX of the website.

**Benefits**
The users will have a quick link if they want to go back to the main page.

- [ ] It will be a UI/UX improvement to add hover states to the links:

**Benefits**
Making them interactive will draw the user's attention toward crucial actions on the page.

Feel free to contact me if anything is unclear and I will be happy to help :pray:
Thanks and happy coding 🥳

**Comment by mirouhml** [comment]
Thanks!
