### ISSUE TITLE
PEER-PEER REVIEW

### ISSUE THREAD

**Issue by Kayonga99** [mirouhml/portfolio#4]
-It would be better to use class instead of ID.
-It would be if you use the same class name for language instead of lang 1, lang 2, and lang 3.
-Maybe use semantic HTML.
-For better and cleaner code it would be better to use  ID attribute to target specific sections.

**Comment by mirouhml** [comment]
Thanks for the suggestions!

**Comment by Kayonga99** [comment]
You are welcome. Sent from Mail for Windows From: Amar HamlaouiSent: Thursday, January 13, 2022 2:25 PMTo: mirouhml/portfolioCc: Kayonga Chiteta; AuthorSubject: Re: [mirouhml/portfolio] PEER-PEER REVIEW (Issue #4) Thanks for the suggestions!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
